add some lines.

diff --git a/install-gathermate b/install-gathermate
--- a/install-gathermate
+++ b/install-gathermate
@@ -10,8 +10,6 @@ PYTHON=python
 eval "$PYTHON"_package=python-minimal
 GIT=git
 eval "$GIT"_package=git
-PIP=pip
-eval "$PIP"_package=python-pip
 
 REPOSITORY=https://github.com/gathermate/gathermate.git
 
@@ -26,6 +24,9 @@ CACHE_PATH=$APPS/tmp
 
 init_common(){
     DAEMON_SCRIPT_PATH=$INIT_PATH/$DAEMON_SCRIPT
+    SERVICE_START="$SERVICE start"
+    SERVICE_STATUS="$SERVICE status"
+    SERVICE_STOP="$SERVICE stop"
 }
 
 init_debian(){
@@ -46,6 +47,8 @@ init_entware(){
     eval "$PYTHON"_package=python-light
     init_common
     SERVICE=$DAEMON_SCRIPT_PATH
+    SERVICE_START="$SERVICE start"
+    SERVICE_STATUS="$SERVICE check"
 }
 
 install_package(){
@@ -62,7 +65,8 @@ install_package(){
             exit 0
             ;;
         *)
-            echo "$PREFIX Invalid option - exit..."
+            echo "$PREFIX Invalid option - uninstall and exit..."
+            uninstall
             exit 1
             ;;
     esac
@@ -144,7 +148,7 @@ check_permission(){
 
 check_packages(){
     echo "$PREFIX Check required packages..."
-    COMMANDS="$PYTHON $PIP $GIT"
+    COMMANDS="$PYTHON $GIT"
     check_commands
     if [ -n "$LIST" ]; then
         OLD_LIST=$LIST
@@ -159,6 +163,7 @@ check_packages(){
         check_commands
         if [ -n "$LIST" ]; then
             echo "$PREFIX Still could not execute $LIST."
+            uninstall
             exit 1
         fi
     fi
@@ -180,13 +185,14 @@ after_install(){
         cp -r $OPT/lib/python2.7/site-packages/lxml* $VENV/lib/python2.7/site-packages
     fi
     mkdir -p $ROOT/var/log $ROOT/var/run
-    $SERVICE start
+    $SERVICE_START
 }
 
 clone_repository(){
     echo "$PREFIX Clone $REPOSITORY..."
     if [ -d "$ROOT" ]; then
         echo "$PREFIX $ROOT already exists."
+        uninstall
         exit 1
     fi
     $GIT clone $REPOSITORY $ROOT
@@ -198,6 +204,7 @@ set_daemon_script(){
         echo "$PREFIX $DAEMON_SCRIPT_PATH exists."
         ORIGIN=$DAEMON_SCRIPT_PATH
         if ! backup_file; then
+            uninstall
             exit 1
         fi
     fi
@@ -208,6 +215,7 @@ set_daemon_script(){
         chmod ug=rwx,o=rx $DAEMON_SCRIPT_PATH
         sed -i -e "s@^ROOT=.*@ROOT=$ROOT@g; s@^ACTIVATE=.*@ACTIVATE=$VENV/bin/activate@g" $DAEMON_SCRIPT_PATH
     else
+        uninstall
         exit 1
     fi
 }
@@ -216,6 +224,7 @@ copy_config(){
     INSTANCE_CONFIG=$ROOT/instance/$CONFIG
     if [ ! -d "$ROOT/instance" ]; then
         if ! mkdir $ROOT/instance; then
+            uninstall
             exit 1
         fi
     fi
@@ -224,40 +233,36 @@ copy_config(){
         echo "$PREFIX $INSTANCE_CONFIG exists."
         ORIGIN=$INSTANCE_CONFIG
         if ! backup_file; then
+            uninstall
             exit 1
         fi
     fi
 
     if ! cp $ROOT/$CONFIG $INSTANCE_CONFIG; then
+        uninstall
         exit 1
     fi
 }
 check_python_version(){
     echo "$PREFIX Check Python version..."
     COMMAND=$PYTHON
-    if ! check_command; then
+    CURRENT_PYTHON=$(get_python_version)
+    if [ "$CURRENT_PYTHON" = "$REQUIRE_PYTHON" ]; then
+        echo "$PREFIX Python $CURRENT_PYTHON exists at $(get_command_path)"
+    else
+        echo "$PREFIX Python $CURRENT_PYTHON is not compatible with this program."
+        PACKAGE=$python_package
+        install_package
         CURRENT_PYTHON=$(get_python_version)
-        if [ "$CURRENT_PYTHON" = "$REQUIRE_PYTHON" ]; then
-            echo "$PREFIX Python $CURRENT_PYTHON exists at $(get_command_path)"
-        else
-            echo "$PREFIX Python $CURRENT_PYTHON is not compatible with this program."
-            PACKAGE=$python_package
-            install_package
-            CURRENT_PYTHON=$(get_python_version)
-            if [ "$CURRENT_PYTHON" != "$REQUIRE_PYTHON" ]; then
-                echo "$PREFIX Python virsion is still $CURRENT_PYTHON"
-                exit 1
-            fi
+        if [ "$CURRENT_PYTHON" != "$REQUIRE_PYTHON" ]; then
+            echo "$PREFIX Python virsion is still $CURRENT_PYTHON"
+            uninstall
+            exit 1
         fi
     fi
 }
 make_virtualenv(){
-    IMPORT_ERROR=$($PIP 2>&1 | sed -r -n -e "s/(ImportError).*/\1/p")
-    if [ "$IMPORT_ERROR" = "ImportError" ]; then
-        $PYTHON -m pip install virtualenv
-    else
-        HOME=$CACHE_PATH $PIP install virtualenv
-    fi
+    #PYTHON_ERROR=$($PYTHON -m virtualenv 2>&1 | sed -r -n -e "s/(No module).*/\1/p")
 
     echo "$PREFIX Make $PYTHON virtual environment at $VENV"
     $PYTHON -m virtualenv $VENV -p $PYTHON
@@ -266,17 +271,19 @@ make_virtualenv(){
         . $VENV/bin/activate
     else
         echo "$PREFIX Could not activate virtual environment."
+        uninstall
         exit 1
     fi
 }
 install_python_packages(){
     if [ ! -e $ROOT/$REQUIREMENTS ]; then
         echo "$PREFIX $ROOT/$REQUIREMENTS is not found."
+        uninstall
         exit 1
     fi
 
     echo "$PREFIX Install Python packages..."
-    PIP_INSTALL_REQUIREMENTS="$PIP install -r $ROOT/$REQUIREMENTS"
+    PIP_INSTALL_REQUIREMENTS="$PYTHON -m pip install -r $ROOT/$REQUIREMENTS"
     if [ -d "$CACHE_PATH" ]; then
         HOME=$CACHE_PATH $PIP_INSTALL_REQUIREMENTS
     else
@@ -287,17 +294,19 @@ install(){
     echo "$PREFIX Install to $TARGET"
     before_install
     clone_repository
-    set_daemon_script
-    copy_config
     check_python_version
     make_virtualenv
     install_python_packages
+    set_daemon_script
+    copy_config
     after_install
 }
 uninstall(){
     echo "$PREFIX Uninstall from $TARGET"
     check_permission
-    $SERVICE stop
+    if $SERVICE_STATUS > /dev/null 2>&1; then
+        $SERVICE_STOP
+    fi
     if [ -e $DAEMON_SCRIPT_PATH ]; then
         echo "$PREFIX Delete $DAEMON_SCRIPT_PATH"
         rm -f $DAEMON_SCRIPT_PATH
@@ -306,7 +315,7 @@ uninstall(){
         echo "$PREFIX Delete $ROOT"
         rm -rf $ROOT
     fi
-    echo "$PREFIX You need to uninstall $PYTHON $PIP $GIT manually if necessary."
+    echo "$PREFIX You need to uninstall $PYTHON $GIT manually if necessary."
     echo "$PREFIX Because it might already exist before installing Gathermate."
 }
 
